apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox1
  namespace: dev-lr

spec:
  selector:
    matchLabels:
       app: 'busy-box' 
  template:
    metadata:
      labels:
        app: 'busy-box'
  
  containers:
  - name: busybox-cnt01
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello from cnt01; sleep 10;done"]
    resources:
      requests:          # requested correspond à ce qu'était demandé au départ, moment de démarrage 
        memory: "100Mi"  # 100 Miga or 100 * 1024 Ko
        cpu: "100m"      # 1 cpu -> 1000 m mili-corpos 
      limits:
        memory: "200Mi"
        cpu: "500m"
  - name: busybox-cnt02
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello from cnt02; sleep 10;done"]
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
  - name: busybox-cnt03
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello from cnt03; sleep 10;done"]
    resources:
      limits:
        memory: "200Mi"
        cpu: "500m"
  - name: busybox-cnt04
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello from cnt04; sleep 10;done"]