
apiVersion: v1
kind: Namespace
metadata:
  name: test-quota
---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
  namespace: test-quota
spec:
  hard:
    requests.cpu: 1
    requests.memory: 1G
    limits.cpu: 2
    limits.memory: 2G
    pods: 3
---