apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default  # dans le namespace per dafaut
rules:
 - apiGroups: [""]
   resources: ["pods"]
   verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader-nmsp
  namespace: default                   # dans le namespace per dafaut
rules:
 - apiGroups: [""]
   resources: ["pods"]
   verbs: ["watch", "list"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole                    # ce s"applqiue sur tout le cluster
metadata:
  name: secret-reader
rules:
 - apiGroups: [""]
   resources: ["secrets"]             # on l'applique sur les secrets 
   verbs: ["get", "watch", "list"]
---