Vagrant.configure("2") do |config|
  config.vm.define "kubemaster" do |kube|
    kube.vm.box = "kwilczynski/ubuntu-16.04-docker"
    kube.vm.hostname = 'kubemaster'

    kube.vm.network :private_network, ip: "192.168.0.42"

    kube.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "kubemaster"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
    end
  end

  config.vm.define "kubenode" do |kubenode|
    kubenode.vm.box = "kwilczynski/ubuntu-16.04-docker"
    kubenode.vm.hostname = 'kubenode'

    kubenode.vm.network :private_network, ip: "192.168.0.43"

    kubenode.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "kubenode"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
    end
  end
end
