FROM nginx:latest


COPY ./index.html /www/files/




EXPOSE 80

CMD ["nginx" ,"-g", "daemon off;"]



#FROM ubuntu:14.04
#MAINTAINER missanchetouani@gmail.com

#COPY . /WORKDIR_ALPINE
#wORKDIR /WORKDIR_ALPINE

#RUN apt-get install -y curl
#RUN apt-get install -y nginx



# https://www.cyberciti.biz/faq/create-a-user-account-on-ubuntu-linux/ to create user and keyssh
#RUN sudo adduser devops # -d /home/devops -m -G sudo devops
#RUN passwd devops 

#RUN set -x \
#     set -e \

	

#EXPOSE 8883


#CMD ["nginx" ,"-g", "daemon off;"]

