apiVersion: v1
kind: Service
metadata:
  name:
  labels:
    app: nginx
  spec:
    selector:
      app: nginx 
    type: LoadBalancer
    ports:
      - ports: 8080
        targetPort: 80
        nodePort: 31200
