
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    zone: fr
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        zone: fr
        env: dev
        app: nginx
    spec:
      containers:
      - name: webbpp 
        image: docker.io/dockernassimchet/nginx_80
        volumeMounts:
        - name: nginx-proxy-config
          mountPath: /html/files
      - name: nginx
        image: docker.io/dockernassimchet/nginx_80
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-proxy-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

