apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31200
