
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    zone: fr
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        zone: fr
        env: dev
        app: nginx
    spec:
      containers:
      - name: "nginx-1" 
        image: docker.io/dockernassimchet/nginx1
        ports:
        - containerPort: 80
      - name: "nginx-2"
        image: docker.io/dockernassimchet/nginx2
        ports:
        - containerPort: 8000

