apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - name: alpine
    image: registry.gitlab.onlineterroir.com/omega/public-reg/alpine:latest
    command:
    - sleep
    - "6000"
  serviceAccountName: sa-nassim-test1