---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service1
  labels:
    app: nginx
spec:
  ports:
  - port: 80
  selector:
    app: nginx1

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service2
  labels:
    app: nginx
spec:
  ports:
  - port: 80
  selector:
    app: nginx2
---