---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high
value: 1000000 
globalDefault: false
description: "This priority class should be used for High priority service pods only."
---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: normal
value: 10000 
globalDefault: false
description: "This priority class should be used for Normal priority service pods only."

--- 
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low
value: 1000
globalDefault: false
description: "This priority class should be used for low priority service pods only."
---
