---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pods-premium
  spec:
    hard:
      cpu: 1
      memory: 500M
      pods: 10
      #configmaps: "10"
      #persistentvolumeclaims: "4"
      #secrets: "10"
      #services: "10"
      #services.loadbalancers: "2"
    scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["premium"]

- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pods-medium
  spec:
    hard:
<<<<<<< HEAD
      cpu: 1
      memory: 700M
=======
      cpu: 1    # 1 cpu
      memory: 700M  
>>>>>>> 245915517a4a094021a869f9639285dd5219aad1
      pods: 5
    scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["normal"]
---
